logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.apache.derby.iapi.jdbc.AutoloadedDriver
    url: jdbc:derby:fazerdb;create=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.DerbyTenFiveDialect
    open-in-view: true
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    resolve-schema-properties: true
  show-login-endpoint: true