server:
  port: 8772
spring:
  datasource:
    driver-class-name: org.apache.derby.iapi.jdbc.AutoloadedDriver
    url: jdbc:derby:fazerdb;create=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.DerbyTenFiveDialect
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub